select "EXAM_SERNO", "REGID", "CUST_ID", "EXAM_CD", "EXAM_SERIES_CD", "REVISION_NUMBER", "FORM_CD", "EXAM_TAKEN_DT", "SCORE", "GRADE", "EXAM_SCALED_SCORE", "SCALED_STATUS", "EXAM_SCORED_DT", "VUEID", "HOLD_FL", "SECTION_ORDINAL", "SECTION_SCALED_SCORE", "NOMINAL_RATING", "SECTION_NAME"
FROM VW_DANB_EXM_EXAM_AND_SECTION
