CREATE OR REPLACE FORCE VIEW "VW_DANB_SBM_SUBMITTAL" ("SUBMITTAL_SERNO", "WKF_SERNO", "SUBMITTAL_ID", "COLLECTION_ID", "SUBCOLLECTION_CD", "TOPIC", "SHORT_TITLE_1", "SHORT_TITLE_2", "DESCR", "PRIMARY_CUST_ID", "CLONEFROM_SUBMITTAL_SERNO", "CREATE_DT", "CREATE_BY", "LAST_CHANGE_DT", "LAST_CHANGE_BY", "ASSIGNED_PROP_ID", "DESCR_WITHOUT_HTML", "PARENT_CUST_ID", "PARENT_SUBMITTAL_SERNO", "SBM_ACCOM", "SBM_ACCOM_APPROVED", "SBM_APP_AUDIT_INFO", "SBM_AUDIT_DIMENSIONAL", "SBM_AUDIT_FL", "SBM_AUTH_EXPIRE", "SBM_PATH", "SBM_BIQ_COURT", "SBM_BIQ_DISCIPLINE", "SBM_BIQ_DOCS", "SBM_BIQ_FELONY", "SBM_BIQ_INSTRUCTIONS", "SBM_BIQ_STATEMENT", "SBM_CDA_EXAM", "SBM_CDA_PATH", "SBM_CDA_PATH3_DOC", "SBM_COA_EXAM", "SBM_COA_PATH", "SBM_COA_PATH4_DOC", "SBM_CPFDA_DOC", "SBM_CPFDA_PATH", "SBM_CPR", "SBM_CRFDA_EXAM", "SBM_CRFDA_PATH", "SBM_CRFDA_PATH2_DOC", "SBM_CRFDA_PATH3_DOC", "SBM_CRFDA_WES", "SBM_DOCS_MAILED", "SBM_EDUC_DEGREE", "SBM_EDUC_INST", "SBM_EDUC_STUDY_AREA", "SBM_EXPIRED", "SBM_FOREIGN_DENTAL", "SBM_FOREIGN_DENTAL_ENG", "SBM_FOREIGN_HS", "SBM_FOREIGN_HS_ENG", "SBM_GRAD_YEAR", "SBM_HIGH_SCHOOL_DOCS", "SBM_INCPLT_RSN", "SBM_INVALID", "SBM_LAST_AUDIT_DT", "SBM_NELDA_GRAD_YEAR", "SBM_NELDA_PATH", "SBM_NELDA_PATH1_DOC", "SBM_NELDA_PATH2_DOC", "SBM_NELDA_PATH3_DOC", "SBM_NELDA_PATH4_DOC", "SBM_NEW_MISSED_ATTEST", "SBM_ORTH_PREP", "SBM_RCT_COND_HOLD", "SBM_RDH_DOCS", "SBM_RECERT_BIQ_COURT", "SBM_RECERT_BIQ_DISCIPLINE", "SBM_RECERT_BIQ_FELONY", "SBM_RECERT_CPR", "SBM_REFUND_ATTEST", "SBM_REFUND_REASON", "SBM_REINSTATE_LVL", "SBM_REQNEW_ATTEST", "SBM_REQNEW_ATTEST_MISSED", "SBM_STAFF_AUDIT_FL", "SBM_STAFF_REVIEW", "SBM_WES_ADDRESS", "SBM_WES_CITY", "SBM_WES_DENTIST", "SBM_WES_EMAIL", "SBM_WES_LIC_NUM", "SBM_WES_LIC_STATE", "SBM_WES_PHONE", "SBM_WES_PRACTICE", "SBM_WES_STATE", "SBM_WES_ZIP", "SBM_WK_EXP") AS 
  SELECT 
        sbm.SUBMITTAL_SERNO, 
WKF_SERNO, 
SUBMITTAL_ID, 
COLLECTION_ID, 
SUBCOLLECTION_CD, 
TOPIC, 
SHORT_TITLE_1, 
SHORT_TITLE_2, 
DESCR, 
PRIMARY_CUST_ID, 
CLONEFROM_SUBMITTAL_SERNO, 
CREATE_DT, 
CREATE_BY, 
LAST_CHANGE_DT , 
LAST_CHANGE_BY, 
ASSIGNED_PROP_ID, 
DESCR_WITHOUT_HTML, 
PARENT_CUST_ID, 
PARENT_SUBMITTAL_SERNO, 
        SBM_ACCOM, 
SBM_ACCOM_APPROVED,
SBM_APP_AUDIT_INFO,
SBM_AUDIT_DIMENSIONAL,
SBM_AUDIT_FL,
SBM_AUTH_EXPIRE,
COALESCE(vsbm.SBM_CDA_PATH, vsbm.SBM_COA_PATH, vsbm.SBM_CPFDA_PATH, vsbm.SBM_CRFDA_PATH, vsbm.SBM_NELDA_PATH) AS SBM_PATH,
SBM_BIQ_COURT,SBM_BIQ_DISCIPLINE,SBM_BIQ_DOCS,SBM_BIQ_FELONY,SBM_BIQ_INSTRUCTIONS,SBM_BIQ_STATEMENT,SBM_CDA_EXAM,SBM_CDA_PATH,SBM_CDA_PATH3_DOC,SBM_COA_EXAM,SBM_COA_PATH,SBM_COA_PATH4_DOC,SBM_CPFDA_DOC,SBM_CPFDA_PATH,SBM_CPR,SBM_CRFDA_EXAM,SBM_CRFDA_PATH,SBM_CRFDA_PATH2_DOC,SBM_CRFDA_PATH3_DOC,SBM_CRFDA_WES,SBM_DOCS_MAILED,SBM_EDUC_DEGREE,SBM_EDUC_INST,SBM_EDUC_STUDY_AREA,SBM_EXPIRED,SBM_FOREIGN_DENTAL,SBM_FOREIGN_DENTAL_ENG,SBM_FOREIGN_HS,SBM_FOREIGN_HS_ENG,SBM_GRAD_YEAR,SBM_HIGH_SCHOOL_DOCS,SBM_INCPLT_RSN,SBM_INVALID,SBM_LAST_AUDIT_DT,SBM_NELDA_GRAD_YEAR,SBM_NELDA_PATH,SBM_NELDA_PATH1_DOC,SBM_NELDA_PATH2_DOC,SBM_NELDA_PATH3_DOC,SBM_NELDA_PATH4_DOC,SBM_NEW_MISSED_ATTEST,SBM_ORTH_PREP,SBM_RCT_COND_HOLD,SBM_RDH_DOCS,SBM_RECERT_BIQ_COURT,SBM_RECERT_BIQ_DISCIPLINE,SBM_RECERT_BIQ_FELONY,SBM_RECERT_CPR,SBM_REFUND_ATTEST,SBM_REFUND_REASON,SBM_REINSTATE_LVL,SBM_REQNEW_ATTEST,SBM_REQNEW_ATTEST_MISSED,SBM_STAFF_AUDIT_FL,SBM_STAFF_REVIEW,SBM_WES_ADDRESS,SBM_WES_CITY,SBM_WES_DENTIST,SBM_WES_EMAIL,SBM_WES_LIC_NUM,SBM_WES_LIC_STATE,SBM_WES_PHONE,SBM_WES_PRACTICE,SBM_WES_STATE,SBM_WES_ZIP,SBM_WK_EXP
FROM SBM_SUBMITTAL sbm
LEFT JOIN VW_DANB_SBM_ATTRIBUTE vsbm on sbm.SUBMITTAL_SERNO  = vsbm.SUBMITTAL_SERNO
/

