CREATE OR REPLACE FORCE VIEW "VW_DANB_CUST_ATTRIBUTE" ("CUST_ID", "CUST_RADIOGRAPHY", "CUST_MAIDEN_NAME", "CUST_RADIOGRAPHY_DATE", "CUST_CERTIFIED_SINCE", "CUST_WORK_STATE", "CUST_CPR_EXPIRATION_DATE", "CUST_DENTAL_OFFICE", "CUST_DECEASED_DATE", "CUST_CPR_BEGIN_DATE") AS 
  select 
CUST_ID,
CUST_RADIOGRAPHY,
CUST_MAIDEN_NAME,
CUST_RADIOGRAPHY_DATE,
CUST_CERTIFIED_SINCE,
CUST_WORK_STATE,
CUST_CPR_EXPIRATION_DATE,
CUST_DENTAL_OFFICE,
CUST_DECEASED_DATE,
CUST_CPR_BEGIN_DATE FROM 

(
SELECT CUST_ID, ATTRIBUTE_TY, ATTRIBUTE_CD, CVAR, NVAR, DVAR 
FROM CEN_CUST_ATTRDTL
)	
	PIVOT ( 
               MAX(
                  COALESCE(CVAR,TO_CHAR(NVAR),TO_CHAR(DVAR),ATTRIBUTE_CD)
                  ) 
	FOR ATTRIBUTE_TY IN (
		
                'CUST_RADIOGRAPHY' AS CUST_RADIOGRAPHY,
                'CUST_MAIDEN_NAME' AS CUST_MAIDEN_NAME,
                'CUST_RADIOGRAPHY_DATE' AS CUST_RADIOGRAPHY_DATE,
                'CUST_CERTIFIED_SINCE' AS CUST_CERTIFIED_SINCE,
                'CUST_WORK_STATE' AS CUST_WORK_STATE,
                'CUST_CPR_EXPIRATION_DATE' AS CUST_CPR_EXPIRATION_DATE,
                'CUST_DENTAL_OFFICE' AS CUST_DENTAL_OFFICE,
                'CUST_DECEASED_DATE' AS CUST_DECEASED_DATE,
                'CUST_CPR_BEGIN_DATE' AS CUST_CPR_BEGIN_DATE
		) 
)
/

