CREATE OR REPLACE FORCE VIEW "VW_DANB_EXM_HIST_SECTION" ("TX_SERNO", "SECTION_ORDINAL", "SECTION_SCALED_SCORE") AS 
  select  
  	TX_SERNO,
  	replace(attribute_cd,'EXAM_SUBCONTENT_','') as SECTION_ORDINAL,
  	nvar as SECTION_SCALED_SCORE
from CEN_CUST_TX_ATTRDTL
where attribute_ty like  'EXAM_SUBCONTENT_%'