CREATE OR REPLACE FORCE VIEW "VW_DANB_CEN_CUST_ATTRIBUTE" ("CUST_ID", "CUST_MAIDEN_NAME", "CUST_BIRTHDATE", "CUST_DECEASED_DATE", "CUST_RADIOGRAPHY", "CUST_RADIOGRAPHY_DATE", "CUST_CERTIFIED_SINCE", "CUST_WORK_STATE", "CUST_CPR_BEGIN_DATE", "CUST_CPR_EXPIRATION_DATE", "CUST_DENTAL_OFFICE", "LAST_PROFILE_UPDATE", "SCHOOL_CLOSED_DATE", "SCHOOL_NELDA", "SCHOOL_OR_ACC_DATE", "SCHOOL_TYPE") AS 
  select 
CUST_ID,
CUST_MAIDEN_NAME,
CUST_BIRTHDATE,
CUST_DECEASED_DATE,
CUST_RADIOGRAPHY,
CUST_RADIOGRAPHY_DATE,
CUST_CERTIFIED_SINCE,
CUST_WORK_STATE,
CUST_CPR_BEGIN_DATE,
CUST_CPR_EXPIRATION_DATE,
CUST_DENTAL_OFFICE,
LAST_PROFILE_UPDATE,
SCHOOL_CLOSED_DATE,
SCHOOL_NELDA,
SCHOOL_OR_ACC_DATE,
SCHOOL_TYPE
FROM 
(
SELECT CUST_ID, ATTRIBUTE_TY, ATTRIBUTE_CD, CVAR, NVAR, DVAR 
FROM CEN_CUST_ATTRDTL
)	
	PIVOT ( 
               MAX(
                  COALESCE(CVAR,TO_CHAR(NVAR),TO_CHAR(DVAR),ATTRIBUTE_CD)
                  ) 
	FOR ATTRIBUTE_TY IN (
                'CUST_MAIDEN_NAME' AS CUST_MAIDEN_NAME,
                'CUST_BIRTHDATE' AS CUST_BIRTHDATE,
                'CUST_DECEASED_DATE' AS CUST_DECEASED_DATE,
                'CUST_RADIOGRAPHY' AS CUST_RADIOGRAPHY,
                'CUST_RADIOGRAPHY_DATE' AS CUST_RADIOGRAPHY_DATE,
                'CUST_CERTIFIED_SINCE' AS CUST_CERTIFIED_SINCE,
                'CUST_WORK_STATE' AS CUST_WORK_STATE,
                'CUST_CPR_BEGIN_DATE' AS CUST_CPR_BEGIN_DATE,
                'CUST_CPR_EXPIRATION_DATE' AS CUST_CPR_EXPIRATION_DATE,
                'CUST_DENTAL_OFFICE' AS CUST_DENTAL_OFFICE,
                'LAST_PROFILE_UPDATE' AS LAST_PROFILE_UPDATE,
                'SCHOOL_CLOSED_DATE' AS SCHOOL_CLOSED_DATE,
                'SCHOOL_NELDA' AS SCHOOL_NELDA,
                'SCHOOL_OR_ACC_DATE' AS SCHOOL_OR_ACC_DATE,
                'SCHOOL_TYPE' AS SCHOOL_TYPE
		) 
)
/
